ies:
  properties:
    message: Welcome to IES - QA
    db-url: jdbc:oracle:thin://localhost:1521/XE
    db-pwd: ies@123
    db-uname: ies_dev
    db-driver-class: OracleDriver
    success-msg: null
    error-msg: null
server:
  port: 7070